version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    versioning-strategy: increase
    commit-message:
      prefix: 'fix(deps):'
      prefix-development: 'chore(deps):'
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'node'
        versions: ['>=23.0.0']
