name: CI and automated releases
on:
  pull_request:
  push:
    branches: [ main, 'gh-readonly-queue/main/**' ]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-compose-ci.yml@main
    with:
      docker_image_local_name: kliento-verifier
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  release:
    needs: ci
    permissions:
      packages: write
      contents: write # To create a Git tag

      # Permissions needed to publish to Pages, although we don't actually use Pages
      pages: write
      id-token: write
    uses: relaycorp/shared-workflows/.github/workflows/server-release.yml@main
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      enable_docs: false
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_PUSH_PASSWORD }}
